package com.iasmim.swing;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iasmimqf
 */
public class CriarFichaMedica extends javax.swing.JFrame {

    /**
     * Creates new form CriarFichaMedica
     */
    public CriarFichaMedica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        medicacaoContGroup = new javax.swing.ButtonGroup();
        tipoAtendimentoGroup = new javax.swing.ButtonGroup();
        alergiaMedicamentosGroup = new javax.swing.ButtonGroup();
        cirurgiaGroup = new javax.swing.ButtonGroup();
        examesGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        medLabel = new javax.swing.JLabel();
        simMed = new javax.swing.JRadioButton();
        naoMed = new javax.swing.JRadioButton();
        medTextField = new javax.swing.JTextField();
        sumplementTextField = new javax.swing.JTextField();
        simSuplementLabel = new javax.swing.JRadioButton();
        suplementLabel = new javax.swing.JLabel();
        naoSuplementButton = new javax.swing.JRadioButton();
        examesTextField = new javax.swing.JTextField();
        naoExamesButton = new javax.swing.JRadioButton();
        simExamesButton = new javax.swing.JRadioButton();
        exameslabel = new javax.swing.JLabel();
        cirurgiasTextField = new javax.swing.JTextField();
        naoCirurgiasButton = new javax.swing.JRadioButton();
        simCirurgiasButton = new javax.swing.JRadioButton();
        cirurgiasLabel = new javax.swing.JLabel();
        alergiaMedTextField = new javax.swing.JTextField();
        naoAlergiaButton = new javax.swing.JRadioButton();
        simAlergiaButton = new javax.swing.JRadioButton();
        alergiaLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queixasTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        tipoAtendimentoLabel = new javax.swing.JLabel();
        urgenciaButton = new javax.swing.JRadioButton();
        emergenciaButton = new javax.swing.JRadioButton();
        rotinaButton = new javax.swing.JRadioButton();

        jButton8.setBackground(new java.awt.Color(205, 255, 232));
        jButton8.setForeground(new java.awt.Color(64, 86, 76));
        jButton8.setText("Adoção");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 251, 216));

        jToolBar1.setBackground(new java.awt.Color(64, 86, 76));
        jToolBar1.setRollover(true);
        jToolBar1.setFloatable(false);

        jButton2.setBackground(new java.awt.Color(205, 255, 232));
        jButton2.setForeground(new java.awt.Color(64, 86, 76));
        jButton2.setText("Início");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton5.setBackground(new java.awt.Color(205, 255, 232));
        jButton5.setForeground(new java.awt.Color(64, 86, 76));
        jButton5.setText("Novo Pet");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton9.setBackground(new java.awt.Color(205, 255, 232));
        jButton9.setForeground(new java.awt.Color(64, 86, 76));
        jButton9.setText("Adoção");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton7.setBackground(new java.awt.Color(205, 255, 232));
        jButton7.setForeground(new java.awt.Color(64, 86, 76));
        jButton7.setText("Histórico");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(filler1);

        jButton4.setBackground(new java.awt.Color(205, 255, 232));
        jButton4.setForeground(new java.awt.Color(64, 86, 76));
        jButton4.setText("Sair");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 63, 56));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/veterinarioIcoon.png"))); // NOI18N
        jLabel1.setText("Ficha Veterinária");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Histórico Clínico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Semibold", 0, 20), new java.awt.Color(48, 63, 56))); // NOI18N
        jPanel2.setOpaque(false);

        medLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel.setForeground(new java.awt.Color(48, 63, 56));
        medLabel.setText("Uso de medicação Contínua?");

        medicacaoContGroup.add(simMed);
        simMed.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simMed.setForeground(new java.awt.Color(48, 63, 56));
        simMed.setText("Sim");
        simMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simMedActionPerformed(evt);
            }
        });

        medicacaoContGroup.add(naoMed);
        naoMed.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoMed.setForeground(new java.awt.Color(48, 63, 56));
        naoMed.setText("Não");

        medTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        medTextField.setForeground(new java.awt.Color(48, 63, 56));

        sumplementTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        sumplementTextField.setForeground(new java.awt.Color(48, 63, 56));

        medicacaoContGroup.add(simSuplementLabel);
        simSuplementLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simSuplementLabel.setForeground(new java.awt.Color(48, 63, 56));
        simSuplementLabel.setText("Sim");
        simSuplementLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simSuplementLabelActionPerformed(evt);
            }
        });

        suplementLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        suplementLabel.setForeground(new java.awt.Color(48, 63, 56));
        suplementLabel.setText("Uso de suplementação?");

        medicacaoContGroup.add(naoSuplementButton);
        naoSuplementButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoSuplementButton.setForeground(new java.awt.Color(48, 63, 56));
        naoSuplementButton.setText("Não");

        examesTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        examesTextField.setForeground(new java.awt.Color(48, 63, 56));

        examesGroup.add(naoExamesButton);
        naoExamesButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoExamesButton.setForeground(new java.awt.Color(48, 63, 56));
        naoExamesButton.setText("Não");

        examesGroup.add(simExamesButton);
        simExamesButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simExamesButton.setForeground(new java.awt.Color(48, 63, 56));
        simExamesButton.setText("Sim");
        simExamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simExamesButtonActionPerformed(evt);
            }
        });

        exameslabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        exameslabel.setForeground(new java.awt.Color(48, 63, 56));
        exameslabel.setText("Fez exames recentes?");

        cirurgiasTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        cirurgiasTextField.setForeground(new java.awt.Color(48, 63, 56));

        cirurgiaGroup.add(naoCirurgiasButton);
        naoCirurgiasButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoCirurgiasButton.setForeground(new java.awt.Color(48, 63, 56));
        naoCirurgiasButton.setText("Não");

        cirurgiaGroup.add(simCirurgiasButton);
        simCirurgiasButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCirurgiasButton.setForeground(new java.awt.Color(48, 63, 56));
        simCirurgiasButton.setText("Sim");
        simCirurgiasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simCirurgiasButtonActionPerformed(evt);
            }
        });

        cirurgiasLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        cirurgiasLabel.setForeground(new java.awt.Color(48, 63, 56));
        cirurgiasLabel.setText("Realizou cirurgias?");

        alergiaMedTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        alergiaMedTextField.setForeground(new java.awt.Color(48, 63, 56));

        alergiaMedicamentosGroup.add(naoAlergiaButton);
        naoAlergiaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoAlergiaButton.setForeground(new java.awt.Color(48, 63, 56));
        naoAlergiaButton.setText("Não");

        alergiaMedicamentosGroup.add(simAlergiaButton);
        simAlergiaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simAlergiaButton.setForeground(new java.awt.Color(48, 63, 56));
        simAlergiaButton.setText("Sim");
        simAlergiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simAlergiaButtonActionPerformed(evt);
            }
        });

        alergiaLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        alergiaLabel.setForeground(new java.awt.Color(48, 63, 56));
        alergiaLabel.setText("Alergia a medicamentos?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medTextField)
                    .addComponent(sumplementTextField)
                    .addComponent(examesTextField)
                    .addComponent(cirurgiasTextField)
                    .addComponent(alergiaMedTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(medLabel)
                                .addGap(51, 51, 51)
                                .addComponent(simMed)
                                .addGap(27, 27, 27)
                                .addComponent(naoMed))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(suplementLabel)
                                .addGap(51, 51, 51)
                                .addComponent(simSuplementLabel)
                                .addGap(27, 27, 27)
                                .addComponent(naoSuplementButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(exameslabel)
                                .addGap(51, 51, 51)
                                .addComponent(simExamesButton)
                                .addGap(27, 27, 27)
                                .addComponent(naoExamesButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cirurgiasLabel)
                                .addGap(51, 51, 51)
                                .addComponent(simCirurgiasButton)
                                .addGap(27, 27, 27)
                                .addComponent(naoCirurgiasButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(alergiaLabel)
                                .addGap(51, 51, 51)
                                .addComponent(simAlergiaButton)
                                .addGap(27, 27, 27)
                                .addComponent(naoAlergiaButton)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel)
                    .addComponent(simMed)
                    .addComponent(naoMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suplementLabel)
                    .addComponent(simSuplementLabel)
                    .addComponent(naoSuplementButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sumplementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exameslabel)
                    .addComponent(simExamesButton)
                    .addComponent(naoExamesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(examesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirurgiasLabel)
                    .addComponent(simCirurgiasButton)
                    .addComponent(naoCirurgiasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cirurgiasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergiaLabel)
                    .addComponent(simAlergiaButton)
                    .addComponent(naoAlergiaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alergiaMedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Queixa Principal e Histórico Recente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Semibold", 0, 20), new java.awt.Color(48, 63, 56))); // NOI18N
        jPanel3.setOpaque(false);

        queixasTextArea.setColumns(20);
        queixasTextArea.setRows(5);
        jScrollPane1.setViewportView(queixasTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        saveButton.setBackground(new java.awt.Color(21, 102, 64));
        saveButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Salvar");
        saveButton.setPreferredSize(new java.awt.Dimension(108, 36));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tipoAtendimentoLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        tipoAtendimentoLabel.setForeground(new java.awt.Color(48, 63, 56));
        tipoAtendimentoLabel.setText("Tipo de atendimento : ");

        tipoAtendimentoGroup.add(urgenciaButton);
        urgenciaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        urgenciaButton.setForeground(new java.awt.Color(48, 63, 56));
        urgenciaButton.setText("Urgência");
        urgenciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgenciaButtonActionPerformed(evt);
            }
        });

        tipoAtendimentoGroup.add(emergenciaButton);
        emergenciaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        emergenciaButton.setForeground(new java.awt.Color(48, 63, 56));
        emergenciaButton.setText("Emergência");

        tipoAtendimentoGroup.add(rotinaButton);
        rotinaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        rotinaButton.setForeground(new java.awt.Color(48, 63, 56));
        rotinaButton.setText("Rotina");
        rotinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotinaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tipoAtendimentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(urgenciaButton)
                                .addGap(18, 18, 18)
                                .addComponent(emergenciaButton)
                                .addGap(18, 18, 18)
                                .addComponent(rotinaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoAtendimentoLabel)
                        .addComponent(urgenciaButton)
                        .addComponent(emergenciaButton)
                        .addComponent(rotinaButton)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void simAlergiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simAlergiaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simAlergiaButtonActionPerformed

    private void simCirurgiasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simCirurgiasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simCirurgiasButtonActionPerformed

    private void simExamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simExamesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simExamesButtonActionPerformed

    private void simSuplementLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simSuplementLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simSuplementLabelActionPerformed

    private void simMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simMedActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void urgenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgenciaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgenciaButtonActionPerformed

    private void rotinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotinaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotinaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarFichaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alergiaLabel;
    private javax.swing.JTextField alergiaMedTextField;
    private javax.swing.ButtonGroup alergiaMedicamentosGroup;
    private javax.swing.ButtonGroup cirurgiaGroup;
    private javax.swing.JLabel cirurgiasLabel;
    private javax.swing.JTextField cirurgiasTextField;
    private javax.swing.JRadioButton emergenciaButton;
    private javax.swing.ButtonGroup examesGroup;
    private javax.swing.JTextField examesTextField;
    private javax.swing.JLabel exameslabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel medLabel;
    private javax.swing.JTextField medTextField;
    private javax.swing.ButtonGroup medicacaoContGroup;
    private javax.swing.JRadioButton naoAlergiaButton;
    private javax.swing.JRadioButton naoCirurgiasButton;
    private javax.swing.JRadioButton naoExamesButton;
    private javax.swing.JRadioButton naoMed;
    private javax.swing.JRadioButton naoSuplementButton;
    private javax.swing.JTextArea queixasTextArea;
    private javax.swing.JRadioButton rotinaButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton simAlergiaButton;
    private javax.swing.JRadioButton simCirurgiasButton;
    private javax.swing.JRadioButton simExamesButton;
    private javax.swing.JRadioButton simMed;
    private javax.swing.JRadioButton simSuplementLabel;
    private javax.swing.JTextField sumplementTextField;
    private javax.swing.JLabel suplementLabel;
    private javax.swing.ButtonGroup tipoAtendimentoGroup;
    private javax.swing.JLabel tipoAtendimentoLabel;
    private javax.swing.JRadioButton urgenciaButton;
    // End of variables declaration//GEN-END:variables
}
