/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iasmim.swing;

import com.arthur.main.TelaPrincipal;
import com.iasmim.swing.FichaAdocao;
import com.iasmim.swing.HistoricoFrame;
import com.joao.model.Funcionario;
import com.joao.model.Animal;
import com.joao.model.Historico;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author iasmimqf
 */
public class CadastroAnimal extends javax.swing.JFrame {

    private Funcionario funcionarioLogado;
    private BufferedImage loadedImage;
    /**
     * Creates new form CadastroAnimal
     */
    
    private ImageIcon animalImage;
    
    public CadastroAnimal(Funcionario funcionario) {
        funcionarioLogado = funcionario;
        initComponents();
        
        imagemPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (loadedImage != null) {
                    // Redimensiona a imagem para caber no JPanel
                    g.drawImage(loadedImage, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        imagemPanel.setPreferredSize(new Dimension(200, 150)); // Define um tamanho preferencial
    }
    
    public void newAnimal() throws IOException {
        String nome = nomeTextField.getText();
        String especie = especieTextField.getText();
        String raca = racaTextField.getText();
        String porte = (String) porteComboBox.getSelectedItem();
        String genero = (String) generoComboBox.getSelectedItem();
        String local = localTextField.getText();
        String speso = pesoTextField.getText();
        String sdataNasc = dataNascTextField.getText();
        String sdataResg = dataResgTextField.getText();
        float peso;
        LocalDate dataNasc, dataResg;
        
        // Verifica se algum dos campos está vazio
        if(nome.isEmpty() || especie.isEmpty() || raca.isEmpty() || porte.isEmpty() || genero.isEmpty() || local.isEmpty() || speso.isEmpty() || sdataNasc.isEmpty() || sdataResg.isEmpty()){
            JOptionPane.showMessageDialog(null, "Antes de cadastrar um novo animal preencha todos os dados!");
            return;
        }

        if(animalImage == null){
            JOptionPane.showMessageDialog(null, "Antes de cadastrar um novo animal adicione a imagem através do botão de Carregar Imagem!");
            return;
        }
        
        //Tentar converter para float
        try {
            peso = Float.parseFloat(speso);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Peso inválido! Use um valor float do peso em quilos.");
            return;
        }
        // Tentar converter para LocalDate (dd/MM/yyyy)
        try {
            dataNasc = LocalDate.parse(sdataNasc, java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            dataResg = LocalDate.parse(sdataResg, java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Data em formato inválido, utilize dd/mm/aaaa");
            return;
        }
        Animal animal = new Animal(dataNasc, local, nome, genero, especie, peso, porte, raca, dataResg);
        animal.setAnimalImage(animalImage);
        HandleJson handleJson = new HandleJson();
        if(handleJson.addAnimalNoArquivo(animal)){
            JOptionPane.showMessageDialog(null, "Animal cadastrado com sucesso!");
            Historico historico = new Historico(animal, true);
            handleJson.AddHistoricoNoArquivo(historico);
            this.dispose();
            TelaPrincipal telaPrincipal = new TelaPrincipal(funcionarioLogado);
            telaPrincipal.setVisible(true);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        incioButton = new javax.swing.JButton();
        adocaoButton = new javax.swing.JButton();
        histButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        especieTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        racaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        porteComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        generoComboBox = new javax.swing.JComboBox<>();
        pesoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataNascTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataResgTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        localTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        imagemPanel = new javax.swing.JPanel();
        imagemEscolhidaLabel = new javax.swing.JLabel();
        carragarImgButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(177, 251, 216));

        jToolBar1.setBackground(new java.awt.Color(64, 86, 76));
        jToolBar1.setRollover(true);

        incioButton.setBackground(new java.awt.Color(205, 255, 232));
        incioButton.setForeground(new java.awt.Color(64, 86, 76));
        incioButton.setText("Início");
        incioButton.setFocusable(false);
        incioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        incioButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        incioButton.setOpaque(true);
        incioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        incioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incioButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(incioButton);

        adocaoButton.setBackground(new java.awt.Color(205, 255, 232));
        adocaoButton.setForeground(new java.awt.Color(64, 86, 76));
        adocaoButton.setText("Adoção");
        adocaoButton.setFocusable(false);
        adocaoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adocaoButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        adocaoButton.setOpaque(true);
        adocaoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adocaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adocaoButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(adocaoButton);

        histButton.setBackground(new java.awt.Color(205, 255, 232));
        histButton.setForeground(new java.awt.Color(64, 86, 76));
        histButton.setText("Histórico");
        histButton.setFocusable(false);
        histButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        histButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        histButton.setOpaque(true);
        histButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        histButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(histButton);
        jToolBar1.add(filler1);

        sairButton.setBackground(new java.awt.Color(205, 255, 232));
        sairButton.setForeground(new java.awt.Color(64, 86, 76));
        sairButton.setText("Sair");
        sairButton.setFocusable(false);
        sairButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        sairButton.setOpaque(true);
        sairButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairButton);

        jLabel1.setBackground(new java.awt.Color(64, 86, 76));
        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novo Pet");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 63, 56));
        jLabel2.setText("Nome : ");

        nomeTextField.setBackground(new java.awt.Color(242, 242, 242));
        nomeTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        nomeTextField.setForeground(new java.awt.Color(32, 61, 74));
        nomeTextField.setText("Nome do animal");
        nomeTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        nomeTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusLost(evt);
            }
        });
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldtFieldActionPerformed(evt);
            }
        });

        especieTextField.setBackground(new java.awt.Color(242, 242, 242));
        especieTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        especieTextField.setForeground(new java.awt.Color(32, 61, 74));
        especieTextField.setText("Espécie");
        especieTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        especieTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        especieTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                especieTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                especieTextFieldFocusLost(evt);
            }
        });
        especieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 63, 56));
        jLabel3.setText("Espécie :");

        racaTextField.setBackground(new java.awt.Color(242, 242, 242));
        racaTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        racaTextField.setForeground(new java.awt.Color(32, 61, 74));
        racaTextField.setText("Raça");
        racaTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        racaTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        racaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                racaTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                racaTextFieldFocusLost(evt);
            }
        });
        racaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racaTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 63, 56));
        jLabel4.setText("Raça : ");

        jLabel5.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 63, 56));
        jLabel5.setText("Porte : ");

        porteComboBox.setBackground(new java.awt.Color(242, 242, 242));
        porteComboBox.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        porteComboBox.setForeground(new java.awt.Color(32, 61, 74));
        porteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Médio", "Grande" }));
        porteComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));

        jLabel6.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 63, 56));
        jLabel6.setText("Gênero :");

        generoComboBox.setBackground(new java.awt.Color(242, 242, 242));
        generoComboBox.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        generoComboBox.setForeground(new java.awt.Color(32, 61, 74));
        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fêmea", "Macho" }));
        generoComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));

        pesoTextField.setBackground(new java.awt.Color(242, 242, 242));
        pesoTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        pesoTextField.setForeground(new java.awt.Color(32, 61, 74));
        pesoTextField.setText("Peso(em Kg)");
        pesoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        pesoTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        pesoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesoTextFieldFocusLost(evt);
            }
        });
        pesoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 63, 56));
        jLabel7.setText("Peso (Kg) :");

        dataNascTextField.setBackground(new java.awt.Color(242, 242, 242));
        dataNascTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        dataNascTextField.setForeground(new java.awt.Color(32, 61, 74));
        dataNascTextField.setText("dd/MM/YYYY");
        dataNascTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        dataNascTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        dataNascTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascTextFieldFocusLost(evt);
            }
        });
        dataNascTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 63, 56));
        jLabel8.setText("Data de Nascimento :");

        dataResgTextField.setBackground(new java.awt.Color(242, 242, 242));
        dataResgTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        dataResgTextField.setForeground(new java.awt.Color(32, 61, 74));
        dataResgTextField.setText("dd/MM/YYYY");
        dataResgTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        dataResgTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        dataResgTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataResgTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataResgTextFieldFocusLost(evt);
            }
        });
        dataResgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataResgTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 63, 56));
        jLabel9.setText("Data de Resgate :");

        localTextField.setBackground(new java.awt.Color(242, 242, 242));
        localTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        localTextField.setForeground(new java.awt.Color(32, 61, 74));
        localTextField.setText("Local");
        localTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        localTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        localTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                localTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                localTextFieldFocusLost(evt);
            }
        });
        localTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 63, 56));
        jLabel10.setText("Local do Resgate :");

        imagemPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout imagemPanelLayout = new javax.swing.GroupLayout(imagemPanel);
        imagemPanel.setLayout(imagemPanelLayout);
        imagemPanelLayout.setHorizontalGroup(
            imagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imagemEscolhidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        imagemPanelLayout.setVerticalGroup(
            imagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imagemEscolhidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        carragarImgButton.setText("Carregar Imagem");
        carragarImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carragarImgButtonActionPerformed(evt);
            }
        });

        cadastrarButton.setBackground(new java.awt.Color(21, 102, 64));
        cadastrarButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cadastrarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrarButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataResgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(especieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(racaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(porteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carragarImgButton)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(especieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(racaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(porteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataNascTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(imagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carragarImgButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataResgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incioButtonActionPerformed
        this.dispose();
        //close();
        TelaPrincipal listScreen = new TelaPrincipal(funcionarioLogado);
        listScreen.setVisible(true);
    }//GEN-LAST:event_incioButtonActionPerformed

    private void adocaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adocaoButtonActionPerformed
        this.dispose();
        FichaAdocao adocaoScreen = new FichaAdocao(funcionarioLogado);
        adocaoScreen.setVisible(true);
    }//GEN-LAST:event_adocaoButtonActionPerformed

    private void histButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histButtonActionPerformed
        this.dispose();
        HistoricoFrame historicoScreen = new HistoricoFrame(funcionarioLogado);
        historicoScreen.setVisible(true);
    }//GEN-LAST:event_histButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void nomeTextFieldtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldtFieldActionPerformed

    private void especieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieTextFieldActionPerformed

    private void racaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racaTextFieldActionPerformed

    private void pesoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextFieldActionPerformed

    private void dataNascTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascTextFieldActionPerformed

    private void dataResgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataResgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataResgTextFieldActionPerformed

    private void localTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localTextFieldActionPerformed

    private void carragarImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carragarImgButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Escolha um arquivo");

        // Filtro de imagens
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().endsWith(".jpg") || file.getName().endsWith(".jpeg") || file.getName().endsWith(".png") || file.getName().endsWith(".gif");
            }

            @Override
            public String getDescription() {
                return "Arquivos de Imagem (*.jpg, *.jpeg, *.png, *.gif)";
            }
        });

        // Exibe o FileChooser e verifica se o usuário selecionou um arquivo
        int result = fileChooser.showOpenDialog(null);

        // Se o usuário clicar em "Abrir"
        if (result == JFileChooser.APPROVE_OPTION) {
            // Obter o arquivo selecionado
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Arquivo escolhido: " + selectedFile.getAbsolutePath());

            try {
                // Tentar carregar a imagem
                loadedImage = ImageIO.read(selectedFile);

                // Se a imagem for nula, significa que não é uma imagem válida
                if (loadedImage == null) {
                    JOptionPane.showMessageDialog(null, "O arquivo selecionado não é uma imagem válida!", "Erro", JOptionPane.ERROR_MESSAGE);
                } else {
                    int width = loadedImage.getWidth();
                    int height = loadedImage.getHeight();

                    // Definindo um tamanho mínimo e máximo em pixels
                    int minWidth = 150, minHeight = 100, maxWidth = 200, maxHeight = 150;

                    if (width < minWidth || height < minHeight || width > maxWidth || height > maxHeight) {
                        JOptionPane.showMessageDialog(null, "A imagem deve ter um tamanho entre " + minWidth + "x" + minHeight + " e " + maxWidth + "x" + maxHeight + " pixels.", "Erro", JOptionPane.ERROR_MESSAGE);
                    } else {
                        animalImage = new ImageIcon(loadedImage);
                        imagemEscolhidaLabel.setIcon(animalImage);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Erro ao ler a imagem!", "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_carragarImgButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        try {
            newAnimal();
        } catch (IOException ex) {
            Logger.getLogger(CadastroAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void nomeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusGained
        // TODO add your handling code here:
        if (nomeTextField.getText().equals("Nome do animal")) {
            nomeTextField.setText("");
        }
    }//GEN-LAST:event_nomeTextFieldFocusGained

    private void nomeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusLost
        // TODO add your handling code here:
        if (nomeTextField.getText().isEmpty()) {
            nomeTextField.setText("Nome do animal");
        }
    }//GEN-LAST:event_nomeTextFieldFocusLost

    private void especieTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_especieTextFieldFocusGained
        // TODO add your handling code here:
        if (especieTextField.getText().equals("Espécie")) {
            especieTextField.setText("");
        }
    }//GEN-LAST:event_especieTextFieldFocusGained

    private void especieTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_especieTextFieldFocusLost
        // TODO add your handling code here:
        if (especieTextField.getText().isEmpty()) {
            especieTextField.setText("Espécie");
        }
    }//GEN-LAST:event_especieTextFieldFocusLost

    private void pesoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoTextFieldFocusGained
        // TODO add your handling code here:
        if (pesoTextField.getText().equals("Peso(em Kg)")) {
            pesoTextField.setText("");
        }
    }//GEN-LAST:event_pesoTextFieldFocusGained

    private void pesoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoTextFieldFocusLost
        // TODO add your handling code here:
        if (pesoTextField.getText().isEmpty()) {
            pesoTextField.setText("Peso(em Kg)");
        }
    }//GEN-LAST:event_pesoTextFieldFocusLost

    private void dataNascTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascTextFieldFocusGained
        // TODO add your handling code here:
        if (dataNascTextField.getText().equals("dd/MM/YYYY")) {
            dataNascTextField.setText("");
        }
    }//GEN-LAST:event_dataNascTextFieldFocusGained

    private void dataNascTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascTextFieldFocusLost
        // TODO add your handling code here:
        if (dataNascTextField.getText().isEmpty()) {
            dataNascTextField.setText("dd/MM/YYYY");
        }
    }//GEN-LAST:event_dataNascTextFieldFocusLost

    private void dataResgTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataResgTextFieldFocusGained
        // TODO add your handling code here:
        if (dataResgTextField.getText().equals("dd/MM/YYYY")) {
            dataResgTextField.setText("");
        }
    }//GEN-LAST:event_dataResgTextFieldFocusGained

    private void dataResgTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataResgTextFieldFocusLost
        // TODO add your handling code here:
        if (dataResgTextField.getText().isEmpty()) {
            dataResgTextField.setText("dd/MM/YYYY");
        }
    }//GEN-LAST:event_dataResgTextFieldFocusLost

    private void localTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_localTextFieldFocusGained
        // TODO add your handling code here:
        if (localTextField.getText().equals("Local")) {
            localTextField.setText("");
        }
    }//GEN-LAST:event_localTextFieldFocusGained

    private void localTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_localTextFieldFocusLost
        // TODO add your handling code here:
        if (localTextField.getText().isEmpty()) {
            localTextField.setText("Local");
        }
    }//GEN-LAST:event_localTextFieldFocusLost

    private void racaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_racaTextFieldFocusGained
        // TODO add your handling code here:
        if (racaTextField.getText().equals("Raça")) {
            racaTextField.setText("");
        }
    }//GEN-LAST:event_racaTextFieldFocusGained

    private void racaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_racaTextFieldFocusLost
        // TODO add your handling code here:
        if (localTextField.getText().isEmpty()) {
            localTextField.setText("Raça");
        }
    }//GEN-LAST:event_racaTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAnimal(new Funcionario()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adocaoButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton carragarImgButton;
    private javax.swing.JTextField dataNascTextField;
    private javax.swing.JTextField dataResgTextField;
    private javax.swing.JTextField especieTextField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JButton histButton;
    private javax.swing.JLabel imagemEscolhidaLabel;
    private javax.swing.JPanel imagemPanel;
    private javax.swing.JButton incioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField localTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JComboBox<String> porteComboBox;
    private javax.swing.JTextField racaTextField;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
