/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iasmim.swing;

import com.arthur.main.TelaPrincipal;
import com.joao.jsonManager.AdotanteDAO;
import com.joao.model.Adotante;
import com.joao.model.CepInfo;
import com.joao.model.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author iasmimqf
 */
public class CadastroAdotante extends javax.swing.JFrame {

    // private final TelaPrincipal inicioForm;
    // private final FichaAdocao telaadocao;
    private Funcionario funcionarioLogado;
    private static AdotanteDAO adotanteDAO = new AdotanteDAO();
    private static CepInfo cepInfo;
    
    public CadastroAdotante(FichaAdocao telaadocao) {
        // this.inicioForm = telainicial;
        //this.telaadocao = telaadocao;
        initComponents();
    }
    public CadastroAdotante() {
        // this.inicioForm = null;
        //this.telaadocao = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefoneField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        cepTextField = new javax.swing.JTextField();
        enderecoField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botaoInicio = new javax.swing.JButton();
        botaoAnimal = new javax.swing.JButton();
        botaoAdocao = new javax.swing.JButton();
        botaoHistorico = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        sairButton = new javax.swing.JButton();
        dataNascimentoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 251, 216));

        jLabel1.setBackground(new java.awt.Color(64, 86, 76));
        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Adotante");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        nomeTextField.setBackground(new java.awt.Color(217, 217, 217));
        nomeTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        nomeTextField.setForeground(new java.awt.Color(32, 61, 74));
        nomeTextField.setText("Nome Completo");
        nomeTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        nomeTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusLost(evt);
            }
        });
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 63, 56));
        jLabel2.setText("Nome : ");

        cpfTextField.setBackground(new java.awt.Color(217, 217, 217));
        cpfTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        cpfTextField.setForeground(new java.awt.Color(32, 61, 74));
        cpfTextField.setText("000.000.000-00");
        cpfTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        cpfTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        cpfTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusLost(evt);
            }
        });
        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 63, 56));
        jLabel3.setText("CPF :");

        telefoneField.setBackground(new java.awt.Color(217, 217, 217));
        telefoneField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        telefoneField.setForeground(new java.awt.Color(32, 61, 74));
        telefoneField.setText("(99) 99999-9999");
        telefoneField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        telefoneField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        telefoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneFieldFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 63, 56));
        jLabel4.setText("Telefone : ");

        jLabel5.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 63, 56));
        jLabel5.setText("E-mail :");

        emailTextField.setBackground(new java.awt.Color(217, 217, 217));
        emailTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(32, 61, 74));
        emailTextField.setText("exemplo@email.com");
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        emailTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 63, 56));
        jLabel7.setText("CEP :");

        cadastrarButton.setBackground(new java.awt.Color(21, 102, 64));
        cadastrarButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cadastrarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrarButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cepTextField.setBackground(new java.awt.Color(217, 217, 217));
        cepTextField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        cepTextField.setForeground(new java.awt.Color(32, 61, 74));
        cepTextField.setText("00000-00");
        cepTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        cepTextField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        cepTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cepTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepTextFieldFocusLost(evt);
            }
        });
        cepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepTextFieldActionPerformed(evt);
            }
        });

        enderecoField.setBackground(new java.awt.Color(217, 217, 217));
        enderecoField.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        enderecoField.setForeground(new java.awt.Color(32, 61, 74));
        enderecoField.setText("Endereço Completo");
        enderecoField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        enderecoField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        enderecoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enderecoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enderecoFieldFocusLost(evt);
            }
        });
        enderecoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 63, 56));
        jLabel8.setText("Endereço :");

        jToolBar1.setBackground(new java.awt.Color(64, 86, 76));
        jToolBar1.setRollover(true);
        jToolBar1.setFloatable(false);

        botaoInicio.setBackground(new java.awt.Color(205, 255, 232));
        botaoInicio.setForeground(new java.awt.Color(64, 86, 76));
        botaoInicio.setText("Início");
        botaoInicio.setFocusable(false);
        botaoInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoInicio.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoInicio.setOpaque(true);
        botaoInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicioActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoInicio);

        botaoAnimal.setBackground(new java.awt.Color(205, 255, 232));
        botaoAnimal.setForeground(new java.awt.Color(64, 86, 76));
        botaoAnimal.setText("Novo Pet");
        botaoAnimal.setFocusable(false);
        botaoAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAnimal.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoAnimal.setOpaque(true);
        botaoAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnimalActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAnimal);

        botaoAdocao.setBackground(new java.awt.Color(205, 255, 232));
        botaoAdocao.setForeground(new java.awt.Color(64, 86, 76));
        botaoAdocao.setText("Adoção");
        botaoAdocao.setFocusable(false);
        botaoAdocao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAdocao.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoAdocao.setOpaque(true);
        botaoAdocao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdocaoActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAdocao);

        botaoHistorico.setBackground(new java.awt.Color(205, 255, 232));
        botaoHistorico.setForeground(new java.awt.Color(64, 86, 76));
        botaoHistorico.setText("Histórico");
        botaoHistorico.setFocusable(false);
        botaoHistorico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoHistorico.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoHistorico.setOpaque(true);
        botaoHistorico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoHistorico);
        jToolBar1.add(filler1);

        sairButton.setBackground(new java.awt.Color(205, 255, 232));
        sairButton.setForeground(new java.awt.Color(64, 86, 76));
        sairButton.setText("Sair");
        sairButton.setFocusable(false);
        sairButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        sairButton.setOpaque(true);
        sairButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairButton);

        dataNascimentoField.setBackground(new java.awt.Color(217, 217, 217));
        dataNascimentoField.setFont(new java.awt.Font("Lato", 2, 18)); // NOI18N
        dataNascimentoField.setForeground(new java.awt.Color(32, 61, 74));
        dataNascimentoField.setText("Data de nascimento (formato: dd/MM/yyyy)");
        dataNascimentoField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 86, 76), 1, true));
        dataNascimentoField.setMargin(new java.awt.Insets(4, 15, 4, 15));
        dataNascimentoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascimentoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoFieldFocusLost(evt);
            }
        });
        dataNascimentoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 63, 56));
        jLabel9.setText("Nascimento :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(23, 23, 23)
                                .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(23, 23, 23)
                                .addComponent(dataNascimentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        Adotante adotante = new Adotante();
        
        String nome = nomeTextField.getText();
        if (!adotante.isNomeValido(nome)) {
            JOptionPane.showMessageDialog(null, "Nome inválido");
            return;
        } 
        
        
        String cpf = cpfTextField.getText();
        
        if(!adotante.validaCpf(cpf)){
            JOptionPane.showMessageDialog(null, "CPF inválido!");
            return;
        }
        
        String cep = cepTextField.getText();
        
        if (!cepInfo.validaCep(cep)) {
            JOptionPane.showMessageDialog(null, "CEP inválido!");
            return;
        }
        if (adotanteDAO.buscarAdotante(cpf).isPresent()){
            JOptionPane.showMessageDialog(null, "Adotante com esse CPF já existe!");
            return;
        }
        
        String email = emailTextField.getText();
        String telefone = telefoneField.getText();
        String endereco = enderecoField.getText();
        String dataNascimento = dataNascimentoField.getText();
        String validacaoDataNascimento = adotante.validarData(dataNascimento);
        
        if (validacaoDataNascimento.equals("Data de nascimento no futuro.") ||
            validacaoDataNascimento.equals("A pessoa tem menos de 18 anos.") ||
            validacaoDataNascimento.equals("Formato de data inválido. Use o formato dd/MM/yyyy.")){
            
            JOptionPane.showMessageDialog(null, validacaoDataNascimento);
            return;
        }
        
        adotante.setNome(nome);
        adotante.setCpf(cpf);
        adotante.setCep(cep);
        adotante.setEmail(email);
        adotante.setTelefone(telefone);
        adotante.setEndereco(endereco);
        
        adotanteDAO.adicionarAdotante(adotante);
        JOptionPane.showMessageDialog(null, "Adotante cadastrado com sucesso!");
        this.dispose();
        FichaAdocao telaAdocao = new FichaAdocao(funcionarioLogado);
        telaAdocao.setVisible(true);
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void enderecoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoFieldActionPerformed

    private void botaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicioActionPerformed
        this.setVisible(false);
        TelaPrincipal telaPrincipal = new TelaPrincipal(funcionarioLogado);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoInicioActionPerformed

    private void botaoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnimalActionPerformed

    }//GEN-LAST:event_botaoAnimalActionPerformed

    private void botaoAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdocaoActionPerformed
        this.dispose();
        FichaAdocao adocaoScreen = new FichaAdocao(funcionarioLogado);
        adocaoScreen.setVisible(true);
    }//GEN-LAST:event_botaoAdocaoActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        this.dispose();
        HistoricoFrame historicoScreen = new HistoricoFrame(funcionarioLogado);
        historicoScreen.setVisible(true);
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
        TelaLogin n = new TelaLogin();
        n.setVisible(true);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void dataNascimentoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoFieldActionPerformed

    private void nomeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusGained
        // TODO add your handling code here:
        if (nomeTextField.getText().equals("Nome Completo")) {
            nomeTextField.setText("");
        }
    }//GEN-LAST:event_nomeTextFieldFocusGained

    private void nomeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusLost
        // TODO add your handling code here:
        if (nomeTextField.getText().isEmpty()) {
            nomeTextField.setText("Nome Completo");
        }
    }//GEN-LAST:event_nomeTextFieldFocusLost

    private void cpfTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusGained
        // TODO add your handling code here:
        if (cpfTextField.getText().equals("000.000.000-00")) {
            cpfTextField.setText("");
        }
    }//GEN-LAST:event_cpfTextFieldFocusGained

    private void cpfTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusLost
        // TODO add your handling code here:
        if (cpfTextField.getText().isEmpty()) {
            cpfTextField.setText("000.000.000-00");
        }
    }//GEN-LAST:event_cpfTextFieldFocusLost

    private void telefoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneFieldFocusGained
        // TODO add your handling code here:
        if (telefoneField.getText().equals("(99) 99999-9999")) {
            telefoneField.setText("");
        }
    }//GEN-LAST:event_telefoneFieldFocusGained

    private void telefoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneFieldFocusLost
        // TODO add your handling code here:
        if (telefoneField.getText().isEmpty()) {
            telefoneField.setText("(99) 99999-9999");
        }
    }//GEN-LAST:event_telefoneFieldFocusLost

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
        if (emailTextField.getText().equals("exemplo@email.com")) {
            emailTextField.setText("");
        }
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        if (emailTextField.getText().isEmpty()) {
            emailTextField.setText("exemplo@email.com");
        }
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void cepTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepTextFieldFocusGained
        // TODO add your handling code here:
        if (cepTextField.getText().equals("00000-00")) {
            cepTextField.setText("");
        }
    }//GEN-LAST:event_cepTextFieldFocusGained

    private void cepTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepTextFieldFocusLost
        // TODO add your handling code here:
        if (cepTextField.getText().isEmpty()) {
            cepTextField.setText("00000-00");
        }
        String cep = cepTextField.getText();
        if (cepInfo.validaCep(cep) && !cepInfo.consultaCep(cep).equals("Erro ao buscar o CEP!")
                && !cepInfo.consultaCep(cep).equals("Erro ao consultar o CEP!")){
            enderecoField.setText(cepInfo.consultaCep(cep));
        }
    }//GEN-LAST:event_cepTextFieldFocusLost

    private void enderecoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoFieldFocusGained
        // TODO add your handling code here:
        if (enderecoField.getText().equals("Endereço Completo")) {
            enderecoField.setText("");
        }
    }//GEN-LAST:event_enderecoFieldFocusGained

    private void enderecoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoFieldFocusLost
        // TODO add your handling code here:
        if (enderecoField.getText().isEmpty()) {
            enderecoField.setText("Endereço Completo");
        }
    }//GEN-LAST:event_enderecoFieldFocusLost

    private void dataNascimentoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFieldFocusGained
        // TODO add your handling code here:
        if (dataNascimentoField.getText().equals("Data de nascimento (formato: dd/MM/yyyy)")) {
            dataNascimentoField.setText("");
        }
    }//GEN-LAST:event_dataNascimentoFieldFocusGained

    private void dataNascimentoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFieldFocusLost
        // TODO add your handling code here:
        if (dataNascimentoField.getText().isEmpty()) {
            dataNascimentoField.setText("Data de nascimento (formato: dd/MM/yyyy)");
        }
    }//GEN-LAST:event_dataNascimentoFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdotante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdocao;
    private javax.swing.JButton botaoAnimal;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoInicio;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JTextField dataNascimentoField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField enderecoField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField telefoneField;
    // End of variables declaration//GEN-END:variables
}
