/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iasmim.swing;

import com.arthur.main.TelaPrincipal;
import com.joao.jsonManager.AdotanteDAO;
import com.joao.model.Adocao;
import com.joao.model.Adotante;
import com.joao.model.Animal;
import com.joao.model.Funcionario;
import com.joao.model.Historico;
import com.joao.model.Termo;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author iasmimqf
 */
public class FichaAdocao extends javax.swing.JFrame {
    
    private Funcionario funcionarioLogado;
    private AdotanteDAO adotanteDAO = new AdotanteDAO();
    private HandleJson handleJson = new HandleJson();
    private List<Animal> animais = handleJson.carregarAnimaisDoArquivo();
    private List<Adotante> adotantes = adotanteDAO.listarAdotantes();
    
    //private final TelaPrincipal inicioForm;
    
    /**
     * Creates new form FichaAdocao
     */
    
    public FichaAdocao(Funcionario funcionario) {
        funcionarioLogado = funcionario;
        initComponents();
        setLocationRelativeTo(null);
        for (Adotante adotante : adotantes) {
            adotanteBox.addItem(adotante.getNome() + ", CPF: " + adotante.getCpf());
        }    
        for (Animal animal : animais){
            animaisBox.addItem(animal.getAnimalNome() + ", id: " + animal.getAnimalID());
        }
    }

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ambienteButtonGroup = new javax.swing.ButtonGroup();
        recebeuAnimalButtonGroup = new javax.swing.ButtonGroup();
        outrosAnimaisButtonGroup = new javax.swing.ButtonGroup();
        mudancaResidenciaButtonGroup = new javax.swing.ButtonGroup();
        conscienciaButtonGroup = new javax.swing.ButtonGroup();
        condicoesFinanceirasButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botaoInicio1 = new javax.swing.JButton();
        botaoAnimal = new javax.swing.JButton();
        botaoHistorico = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botaoSair = new javax.swing.JButton();
        salvarAdocaoButton = new javax.swing.JButton();
        adotanteBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataAdocaoField = new javax.swing.JFormattedTextField();
        animaisBox = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        medLabel = new javax.swing.JLabel();
        simOutrosAnimaisButton = new javax.swing.JRadioButton();
        naoOutrosAnimaisButton = new javax.swing.JRadioButton();
        outrosAnimaisTextField = new javax.swing.JTextField();
        simCondicoesFinancButton = new javax.swing.JLabel();
        naoCondicoesFinancButton = new javax.swing.JRadioButton();
        simMed1 = new javax.swing.JRadioButton();
        medLabel2 = new javax.swing.JLabel();
        medLabel3 = new javax.swing.JLabel();
        apartamentoButton = new javax.swing.JRadioButton();
        casaButton = new javax.swing.JRadioButton();
        quintalButton = new javax.swing.JRadioButton();
        simCondicoesFinancButton1 = new javax.swing.JLabel();
        localDuranteViagemTextField = new javax.swing.JTextField();
        medLabel4 = new javax.swing.JLabel();
        levoComigoButton = new javax.swing.JRadioButton();
        devolvoAdocaoButton = new javax.swing.JRadioButton();
        entregoPessoButton = new javax.swing.JRadioButton();
        medLabel5 = new javax.swing.JLabel();
        simMed2 = new javax.swing.JRadioButton();
        naoCondicoesFinancButton1 = new javax.swing.JRadioButton();
        medLabel6 = new javax.swing.JLabel();
        recebeuAnimalButton = new javax.swing.JRadioButton();
        naoRecebeuAnimalButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 251, 216));

        jLabel1.setBackground(new java.awt.Color(64, 86, 76));
        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ficha de Adoção");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 63, 56));
        jLabel2.setText("Data :");

        jToolBar1.setBackground(new java.awt.Color(64, 86, 76));
        jToolBar1.setRollover(true);
        jToolBar1.setFloatable(false);

        botaoInicio1.setBackground(new java.awt.Color(205, 255, 232));
        botaoInicio1.setForeground(new java.awt.Color(64, 86, 76));
        botaoInicio1.setText("Início");
        botaoInicio1.setFocusable(false);
        botaoInicio1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoInicio1.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoInicio1.setOpaque(true);
        botaoInicio1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicio1ActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoInicio1);

        botaoAnimal.setBackground(new java.awt.Color(205, 255, 232));
        botaoAnimal.setForeground(new java.awt.Color(64, 86, 76));
        botaoAnimal.setText("Novo Pet");
        botaoAnimal.setFocusable(false);
        botaoAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAnimal.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoAnimal.setOpaque(true);
        botaoAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnimalActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAnimal);

        botaoHistorico.setBackground(new java.awt.Color(205, 255, 232));
        botaoHistorico.setForeground(new java.awt.Color(64, 86, 76));
        botaoHistorico.setText("Histórico");
        botaoHistorico.setFocusable(false);
        botaoHistorico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoHistorico.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoHistorico.setOpaque(true);
        botaoHistorico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoHistorico);
        jToolBar1.add(filler1);

        botaoSair.setBackground(new java.awt.Color(205, 255, 232));
        botaoSair.setForeground(new java.awt.Color(64, 86, 76));
        botaoSair.setText("Sair");
        botaoSair.setFocusable(false);
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSair.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoSair.setOpaque(true);
        botaoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoSair);

        salvarAdocaoButton.setBackground(new java.awt.Color(21, 102, 64));
        salvarAdocaoButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        salvarAdocaoButton.setForeground(new java.awt.Color(255, 255, 255));
        salvarAdocaoButton.setText("Salvar");
        salvarAdocaoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salvarAdocaoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarAdocaoButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        salvarAdocaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAdocaoButtonActionPerformed(evt);
            }
        });

        adotanteBox.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        adotanteBox.setPreferredSize(new java.awt.Dimension(64, 24));
        adotanteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adotanteBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 63, 56));
        jLabel3.setText("Adotante :");

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 63, 56));
        jLabel4.setText("Animal :");

        dataAdocaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dataAdocaoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataAdocaoField.setToolTipText("20/02/2002");
        dataAdocaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAdocaoFieldActionPerformed(evt);
            }
        });

        animaisBox.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        animaisBox.setPreferredSize(new java.awt.Dimension(64, 24));

        jButton6.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(32, 61, 74));
        jButton6.setText("<html><u>Cadastre um novo adotante</u></html> ");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termo de Responsabilidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Semibold", 0, 20), new java.awt.Color(48, 63, 56))); // NOI18N
        jPanel3.setOpaque(false);

        medLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel.setForeground(new java.awt.Color(48, 63, 56));
        medLabel.setText("Tem mais animais em casa?");

        outrosAnimaisButtonGroup.add(simOutrosAnimaisButton);
        simOutrosAnimaisButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simOutrosAnimaisButton.setForeground(new java.awt.Color(48, 63, 56));
        simOutrosAnimaisButton.setText("Sim");
        simOutrosAnimaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simOutrosAnimaisButtonActionPerformed(evt);
            }
        });

        outrosAnimaisButtonGroup.add(naoOutrosAnimaisButton);
        naoOutrosAnimaisButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoOutrosAnimaisButton.setForeground(new java.awt.Color(48, 63, 56));
        naoOutrosAnimaisButton.setText("Não");
        naoOutrosAnimaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoOutrosAnimaisButtonActionPerformed(evt);
            }
        });

        outrosAnimaisTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        outrosAnimaisTextField.setForeground(new java.awt.Color(48, 63, 56));

        simCondicoesFinancButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCondicoesFinancButton.setForeground(new java.awt.Color(48, 63, 56));
        simCondicoesFinancButton.setText("Quais ?");

        condicoesFinanceirasButtonGroup.add(naoCondicoesFinancButton);
        naoCondicoesFinancButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoCondicoesFinancButton.setForeground(new java.awt.Color(48, 63, 56));
        naoCondicoesFinancButton.setText("Não");

        condicoesFinanceirasButtonGroup.add(simMed1);
        simMed1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simMed1.setForeground(new java.awt.Color(48, 63, 56));
        simMed1.setText("Sim");
        simMed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simMed1ActionPerformed(evt);
            }
        });

        medLabel2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel2.setForeground(new java.awt.Color(48, 63, 56));
        medLabel2.setText("Tem condições financeiras para levar o animal que está adotando ao veterinário ?");

        medLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel3.setForeground(new java.awt.Color(48, 63, 56));
        medLabel3.setText("Em que tipo de ambiente o animal ficará?");

        ambienteButtonGroup.add(apartamentoButton);
        apartamentoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        apartamentoButton.setForeground(new java.awt.Color(48, 63, 56));
        apartamentoButton.setText("Apartamento");
        apartamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartamentoButtonActionPerformed(evt);
            }
        });

        ambienteButtonGroup.add(casaButton);
        casaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        casaButton.setForeground(new java.awt.Color(48, 63, 56));
        casaButton.setText("Casa");

        ambienteButtonGroup.add(quintalButton);
        quintalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        quintalButton.setForeground(new java.awt.Color(48, 63, 56));
        quintalButton.setText("Quintal");
        quintalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quintalButtonActionPerformed(evt);
            }
        });

        simCondicoesFinancButton1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCondicoesFinancButton1.setForeground(new java.awt.Color(48, 63, 56));
        simCondicoesFinancButton1.setText("Quando viajar aonde pensa em deixar o animal?");

        localDuranteViagemTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        localDuranteViagemTextField.setForeground(new java.awt.Color(48, 63, 56));

        medLabel4.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel4.setForeground(new java.awt.Color(48, 63, 56));
        medLabel4.setText("Se mudar de residência o que fará com o animal?");

        mudancaResidenciaButtonGroup.add(levoComigoButton);
        levoComigoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        levoComigoButton.setForeground(new java.awt.Color(48, 63, 56));
        levoComigoButton.setText("Levo comigo");
        levoComigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levoComigoButtonActionPerformed(evt);
            }
        });

        mudancaResidenciaButtonGroup.add(devolvoAdocaoButton);
        devolvoAdocaoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        devolvoAdocaoButton.setForeground(new java.awt.Color(48, 63, 56));
        devolvoAdocaoButton.setText("Devolvo para adoção");

        mudancaResidenciaButtonGroup.add(entregoPessoButton);
        entregoPessoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        entregoPessoButton.setForeground(new java.awt.Color(48, 63, 56));
        entregoPessoButton.setText("Entrego a outra pessoa");
        entregoPessoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregoPessoButtonActionPerformed(evt);
            }
        });

        medLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel5.setForeground(new java.awt.Color(48, 63, 56));
        medLabel5.setText("Tem consciência de que um animal pode viver até 10, 15, 18 anos? E que se torna responsável por ele durante toda a sua vida?");

        conscienciaButtonGroup.add(simMed2);
        simMed2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simMed2.setForeground(new java.awt.Color(48, 63, 56));
        simMed2.setText("Sim");
        simMed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simMed2ActionPerformed(evt);
            }
        });

        conscienciaButtonGroup.add(naoCondicoesFinancButton1);
        naoCondicoesFinancButton1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoCondicoesFinancButton1.setForeground(new java.awt.Color(48, 63, 56));
        naoCondicoesFinancButton1.setText("Não");

        medLabel6.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel6.setForeground(new java.awt.Color(48, 63, 56));
        medLabel6.setText("Já entregou algum animal para adoção/abrigo");

        recebeuAnimalButtonGroup.add(recebeuAnimalButton);
        recebeuAnimalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        recebeuAnimalButton.setForeground(new java.awt.Color(48, 63, 56));
        recebeuAnimalButton.setText("Sim");
        recebeuAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeuAnimalButtonActionPerformed(evt);
            }
        });

        recebeuAnimalButtonGroup.add(naoRecebeuAnimalButton);
        naoRecebeuAnimalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoRecebeuAnimalButton.setForeground(new java.awt.Color(48, 63, 56));
        naoRecebeuAnimalButton.setText("Não");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel)
                        .addGap(51, 51, 51)
                        .addComponent(simOutrosAnimaisButton)
                        .addGap(27, 27, 27)
                        .addComponent(naoOutrosAnimaisButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simCondicoesFinancButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outrosAnimaisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(medLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(apartamentoButton)
                                .addGap(27, 27, 27)
                                .addComponent(casaButton)
                                .addGap(31, 31, 31)
                                .addComponent(quintalButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(medLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(simMed1)))
                        .addGap(27, 27, 27)
                        .addComponent(naoCondicoesFinancButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simCondicoesFinancButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(localDuranteViagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel4)
                        .addGap(51, 51, 51)
                        .addComponent(levoComigoButton)
                        .addGap(27, 27, 27)
                        .addComponent(devolvoAdocaoButton)
                        .addGap(31, 31, 31)
                        .addComponent(entregoPessoButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel5)
                        .addGap(51, 51, 51)
                        .addComponent(simMed2)
                        .addGap(27, 27, 27)
                        .addComponent(naoCondicoesFinancButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel6)
                        .addGap(51, 51, 51)
                        .addComponent(recebeuAnimalButton)
                        .addGap(27, 27, 27)
                        .addComponent(naoRecebeuAnimalButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel)
                    .addComponent(simOutrosAnimaisButton)
                    .addComponent(naoOutrosAnimaisButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outrosAnimaisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simCondicoesFinancButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel2)
                    .addComponent(simMed1)
                    .addComponent(naoCondicoesFinancButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel3)
                    .addComponent(apartamentoButton)
                    .addComponent(casaButton)
                    .addComponent(quintalButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localDuranteViagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simCondicoesFinancButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel4)
                    .addComponent(levoComigoButton)
                    .addComponent(devolvoAdocaoButton)
                    .addComponent(entregoPessoButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel5)
                    .addComponent(simMed2)
                    .addComponent(naoCondicoesFinancButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel6)
                    .addComponent(recebeuAnimalButton)
                    .addComponent(naoRecebeuAnimalButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dataAdocaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(animaisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(adotanteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(salvarAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(dataAdocaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(adotanteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animaisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(salvarAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarAdocaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAdocaoButtonActionPerformed
        // TODO add your handling code here:
        String cpf = adotanteBox.getSelectedItem().toString().substring(adotanteBox.getSelectedItem().toString().length() - 11);
        Adotante adotante = adotanteDAO.buscarAdotante(cpf).get();
        
        String id = animaisBox.getSelectedItem().toString().substring(animaisBox.getSelectedItem().toString().indexOf("id: ") + 4).trim();
        Animal animal = handleJson.buscarAnimalPeloId(id);
        
        boolean temOutrosAnimais = false;
        String outrosAnimais = "";
        boolean temOutrosAnimaisSelecionado = false;
        for(AbstractButton button : Collections.list(outrosAnimaisButtonGroup.getElements())){
            if (button.isSelected()) {
                temOutrosAnimaisSelecionado = true;
                if (button.getText().equals("Sim")){
                    temOutrosAnimais = true;
                    outrosAnimais = outrosAnimaisTextField.getText();
                    if (outrosAnimais.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Insira os outros animais.");
                        return;
                    }
                }
                else {
                    temOutrosAnimais = false;
                }
                break;
            }
        }
        
        boolean podeLevarAoVet = false;
        boolean podeLevarAoVetSelecionado = false;
        for( AbstractButton button : Collections.list(condicoesFinanceirasButtonGroup.getElements())){
            if(button.isSelected()){
                podeLevarAoVetSelecionado = true;
                podeLevarAoVet = button.getText().equals("Sim") ? true : false;
                break;
            }
        }
        
        String ambiente = null;
        boolean ambienteSelecionado = false;
        for( AbstractButton button : Collections.list(ambienteButtonGroup.getElements())){
            if(button.isSelected()){
                ambienteSelecionado = true;
                ambiente = button.getText();
                break;
            }
        }
        
        String localDuranteViagem = localDuranteViagemTextField.getText();
        if (localDuranteViagem.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todo o formulário!");
            return;
        }
        
        String oqueFaraSeMudar = null;
        boolean oqueFaraPreenchido = false;
        for( AbstractButton button : Collections.list(mudancaResidenciaButtonGroup.getElements())){
            if(button.isSelected()){
                oqueFaraPreenchido = true;
                oqueFaraSeMudar = button.getText();
                break;
            }
        }
        
        boolean consciencia = false;
        boolean conscienciaPreenchida = false;
        for( AbstractButton button : Collections.list(conscienciaButtonGroup.getElements())){
            if(button.isSelected()){
                conscienciaPreenchida = true;
                consciencia = button.getText().equals("Sim") ? true : false;
                break;
            }
        }
        
        
        boolean jaEntregouParaAdocao = false;
        boolean jaEntregouPreenchida = false;
        for( AbstractButton button : Collections.list(recebeuAnimalButtonGroup.getElements())){
            if(button.isSelected()){
                jaEntregouPreenchida = true;
                jaEntregouParaAdocao = button.getText().equals("Sim") ? true : false;
                break;
            }
        }
        
        boolean formularioPreenchido = jaEntregouPreenchida && conscienciaPreenchida
                && oqueFaraPreenchido && ambienteSelecionado && podeLevarAoVetSelecionado
                && temOutrosAnimaisSelecionado;
        
        if (!formularioPreenchido) {
            JOptionPane.showMessageDialog(null, "Preencha todo o formulário!");
        }
        
        Termo termoResponsabilidade = new Termo(temOutrosAnimais,outrosAnimais,
        podeLevarAoVet, ambiente, localDuranteViagem, oqueFaraSeMudar, consciencia,
        jaEntregouParaAdocao);
        
        Adocao adocao = new Adocao(termoResponsabilidade, adotante, animal);
        
        String dataAdocao = dataAdocaoField.getText();
        
        if (!adocao.validarData(dataAdocao).equals("true")){
            JOptionPane.showMessageDialog(null, adocao.validarData(dataAdocao));
            return;
        }
        
        adocao.setDataAdocao(LocalDate.parse(dataAdocao, DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        
        System.out.println("Adoção sendo cadastrada no sistema...");
        animal.setAnimalAdocao(adocao);
        ArrayList <Adocao> animaisAdotados = adotante.getAnimaisAdotados();
        animaisAdotados.add(adocao);
        adotante.setAnimaisAdotados(animaisAdotados);
        
        handleJson.atualizarAnimal(animal.getAnimalID(), animal);
        adotanteDAO.atualizarAdotante(adotante.getCpf(), adotante);
        Historico historico = new Historico(animal, adocao);
        try {
            handleJson.AddHistoricoNoArquivo(historico);
        } catch (IOException ex) {
            System.out.println("Erro ao tentar adicionar a adoção ao histórico.");
        }
        
        System.out.println("Adoção cadastrada com sucesso!");
        
        this.dispose();
        TelaPrincipal telaPrincipal = new TelaPrincipal(funcionarioLogado);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_salvarAdocaoButtonActionPerformed

    private void dataAdocaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAdocaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAdocaoFieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //this.setVisible(false);
        
        this.dispose();
        CadastroAdotante adotanteScreen = new CadastroAdotante();
        adotanteScreen.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void adotanteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adotanteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adotanteBoxActionPerformed

    private void simOutrosAnimaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simOutrosAnimaisButtonActionPerformed
        // TODO add your handling code here:
        outrosAnimaisTextField.setEnabled(true);
    }//GEN-LAST:event_simOutrosAnimaisButtonActionPerformed

    private void simMed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simMed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simMed1ActionPerformed

    private void apartamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartamentoButtonActionPerformed

    private void quintalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quintalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quintalButtonActionPerformed

    private void levoComigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levoComigoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levoComigoButtonActionPerformed

    private void entregoPessoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregoPessoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entregoPessoButtonActionPerformed

    private void simMed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simMed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simMed2ActionPerformed

    private void recebeuAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeuAnimalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeuAnimalButtonActionPerformed

    private void botaoInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicio1ActionPerformed
        this.dispose();
        TelaPrincipal mainScreen = new TelaPrincipal(funcionarioLogado);
        mainScreen.setVisible(true);
    }//GEN-LAST:event_botaoInicio1ActionPerformed

    private void botaoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnimalActionPerformed
        this.dispose();
        CadastroAnimal newPetScreen = new CadastroAnimal(funcionarioLogado);
        newPetScreen.setVisible(true);
    }//GEN-LAST:event_botaoAnimalActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        this.dispose();
        HistoricoFrame historicoScreen = new HistoricoFrame(funcionarioLogado);
        historicoScreen.setVisible(true);
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
        TelaLogin n = new TelaLogin();
        n.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void naoOutrosAnimaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoOutrosAnimaisButtonActionPerformed
        // TODO add your handling code here:
        outrosAnimaisTextField.setEnabled(false);
        outrosAnimaisTextField.setText("");
    }//GEN-LAST:event_naoOutrosAnimaisButtonActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        ////<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaAdocao(new Funcionario()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adotanteBox;
    private javax.swing.ButtonGroup ambienteButtonGroup;
    private javax.swing.JComboBox<String> animaisBox;
    private javax.swing.JRadioButton apartamentoButton;
    private javax.swing.JButton botaoAnimal;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoInicio1;
    private javax.swing.JButton botaoSair;
    private javax.swing.JRadioButton casaButton;
    private javax.swing.ButtonGroup condicoesFinanceirasButtonGroup;
    private javax.swing.ButtonGroup conscienciaButtonGroup;
    private javax.swing.JFormattedTextField dataAdocaoField;
    private javax.swing.JRadioButton devolvoAdocaoButton;
    private javax.swing.JRadioButton entregoPessoButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton levoComigoButton;
    private javax.swing.JTextField localDuranteViagemTextField;
    private javax.swing.JLabel medLabel;
    private javax.swing.JLabel medLabel2;
    private javax.swing.JLabel medLabel3;
    private javax.swing.JLabel medLabel4;
    private javax.swing.JLabel medLabel5;
    private javax.swing.JLabel medLabel6;
    private javax.swing.ButtonGroup mudancaResidenciaButtonGroup;
    private javax.swing.JRadioButton naoCondicoesFinancButton;
    private javax.swing.JRadioButton naoCondicoesFinancButton1;
    private javax.swing.JRadioButton naoOutrosAnimaisButton;
    private javax.swing.JRadioButton naoRecebeuAnimalButton;
    private javax.swing.ButtonGroup outrosAnimaisButtonGroup;
    private javax.swing.JTextField outrosAnimaisTextField;
    private javax.swing.JRadioButton quintalButton;
    private javax.swing.JRadioButton recebeuAnimalButton;
    private javax.swing.ButtonGroup recebeuAnimalButtonGroup;
    private javax.swing.JButton salvarAdocaoButton;
    private javax.swing.JLabel simCondicoesFinancButton;
    private javax.swing.JLabel simCondicoesFinancButton1;
    private javax.swing.JRadioButton simMed1;
    private javax.swing.JRadioButton simMed2;
    private javax.swing.JRadioButton simOutrosAnimaisButton;
    // End of variables declaration//GEN-END:variables
}
