/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iasmim.swing;

import com.arthur.main.TelaPrincipal;
import com.joao.jsonManager.AdotanteJsonHandler;
import com.joao.model.Adocao;
import com.joao.model.Adotante;
import com.joao.model.Animal;
import com.joao.model.Funcionario;
import com.joao.model.Historico;
import com.joao.model.Termo;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class VisualizarAdocao extends javax.swing.JFrame {

    private Funcionario funcionarioLogado;
    private Animal animal;
    private Adocao adocaoOriginal;
    private AdotanteJsonHandler adotanteDAO = new AdotanteJsonHandler();
    private HandleJson handleJson = new HandleJson();
    
    /**
     * Creates new form visualizarAdocao
     */
    public VisualizarAdocao(Animal animal, Funcionario funcionario) {
        initComponents();
        
        this.funcionarioLogado = funcionario;
        this.animal = animal;
        Adocao adocao = animal.getAnimalAdocao();
        adocaoOriginal = adocao;
        Termo termo = adocao.getTermoResponsabilidade();
        
        dataAdocaoField.setText(adocao.getDataAdocao().format(
                DateTimeFormatter.ofPattern("dd-MM-yyyy"
                )).replace("-", "/"));
        
        adotanteBox.addItem(adocao.getAdotante().getNome() + ", CPF: " + 
                adocao.getAdotante().getCpf());
        
        animaisBox.addItem(animal.getAnimalNome() + ", id: " + animal.getAnimalID());
        
        if (termo.isTemOutrosAnimais()){
            simOutrosAnimaisButton.setSelected(true);
            outrosAnimaisTextField.setText(termo.getOutrosAnimais());
        } else{
            naoOutrosAnimaisButton.setSelected(true);
        }
        
        localDuranteViagemTextField.setText(termo.getLocalDuranteViagem());
        
        if (termo.isConsciencia()){
            simConscienciaButton.setSelected(true);
        } else {
            naoConscienciaButton.setSelected(true);
        }
        if (termo.isJaEntregouParaAdocao()){
            entregouAnimalButton.setSelected(true);
        } else {
            naoEntregouAnimalButton.setSelected(true);
        }
        if (termo.isPodeLevarAoVet()){
            simCondicoes.setSelected(true);
        } else {
            naoCondicoes.setSelected(true);
        }
        
        String ambiente = termo.getAmbiente();
        
        if (ambiente.equals("Apartamento")){
            apartamentoButton.setSelected(true);
        } 
        else if (ambiente.equals("Casa")) {
            casaButton.setSelected(true);
        } 
        else {
            quintalButton.setSelected(true);
        }
        
        String acaoSeMudar = termo.getAcaoSeFizerMudanca();
        if (acaoSeMudar.equals("Levo Comigo")){
            levoComigoButton.setSelected(true);
        } else if (acaoSeMudar.equals("Devolvo para adoção")){
            devolvoAdocaoButton.setSelected(true);
        } else {
            entregoPessoButton.setSelected(true);
        }
        
    }

    public VisualizarAdocao() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maisAnimaisEmCasaButtongroup = new javax.swing.ButtonGroup();
        condicoesButtonGroup = new javax.swing.ButtonGroup();
        ambienteButtonGrouṕ = new javax.swing.ButtonGroup();
        seMudarButtonGroup = new javax.swing.ButtonGroup();
        conscienciaButtonGroup = new javax.swing.ButtonGroup();
        entregouPraAdocaoButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botaoFechar = new javax.swing.JButton();
        salvarAdocaoButton = new javax.swing.JButton();
        adotanteBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataAdocaoField = new javax.swing.JFormattedTextField();
        animaisBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        medLabel = new javax.swing.JLabel();
        simOutrosAnimaisButton = new javax.swing.JRadioButton();
        naoOutrosAnimaisButton = new javax.swing.JRadioButton();
        outrosAnimaisTextField = new javax.swing.JTextField();
        simCondicoesFinancButton = new javax.swing.JLabel();
        naoCondicoes = new javax.swing.JRadioButton();
        simCondicoes = new javax.swing.JRadioButton();
        medLabel2 = new javax.swing.JLabel();
        medLabel3 = new javax.swing.JLabel();
        apartamentoButton = new javax.swing.JRadioButton();
        casaButton = new javax.swing.JRadioButton();
        quintalButton = new javax.swing.JRadioButton();
        simCondicoesFinancButton1 = new javax.swing.JLabel();
        localDuranteViagemTextField = new javax.swing.JTextField();
        medLabel4 = new javax.swing.JLabel();
        levoComigoButton = new javax.swing.JRadioButton();
        devolvoAdocaoButton = new javax.swing.JRadioButton();
        entregoPessoButton = new javax.swing.JRadioButton();
        medLabel5 = new javax.swing.JLabel();
        simConscienciaButton = new javax.swing.JRadioButton();
        naoConscienciaButton = new javax.swing.JRadioButton();
        medLabel6 = new javax.swing.JLabel();
        entregouAnimalButton = new javax.swing.JRadioButton();
        naoEntregouAnimalButton = new javax.swing.JRadioButton();
        editarCheckBox = new javax.swing.JCheckBox();
        excluirAdocaoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 251, 216));
        salvarAdocaoButton.setVisible(false);
        excluirAdocaoButton.setVisible(false);

        jLabel1.setBackground(new java.awt.Color(64, 86, 76));
        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ficha de Adoção");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 63, 56));
        jLabel2.setText("Data :");

        jToolBar1.setBackground(new java.awt.Color(64, 86, 76));
        jToolBar1.setRollover(true);
        jToolBar1.setFloatable(false);
        jToolBar1.add(filler1);

        botaoFechar.setBackground(new java.awt.Color(205, 255, 232));
        botaoFechar.setForeground(new java.awt.Color(64, 86, 76));
        botaoFechar.setText("Fechar");
        botaoFechar.setFocusable(false);
        botaoFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoFechar.setMargin(new java.awt.Insets(4, 14, 4, 14));
        botaoFechar.setOpaque(true);
        botaoFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoFechar);

        salvarAdocaoButton.setBackground(new java.awt.Color(21, 102, 64));
        salvarAdocaoButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        salvarAdocaoButton.setForeground(new java.awt.Color(255, 255, 255));
        salvarAdocaoButton.setText("Salvar");
        salvarAdocaoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salvarAdocaoButton.setEnabled(false);
        salvarAdocaoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarAdocaoButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        salvarAdocaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAdocaoButtonActionPerformed(evt);
            }
        });

        adotanteBox.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        adotanteBox.setEnabled(false);
        adotanteBox.setPreferredSize(new java.awt.Dimension(64, 24));
        adotanteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adotanteBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 63, 56));
        jLabel3.setText("Adotante :");

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 63, 56));
        jLabel4.setText("Animal :");

        dataAdocaoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dataAdocaoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataAdocaoField.setToolTipText("20/02/2002");
        dataAdocaoField.setEnabled(false);
        dataAdocaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAdocaoFieldActionPerformed(evt);
            }
        });

        animaisBox.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        animaisBox.setEnabled(false);
        animaisBox.setPreferredSize(new java.awt.Dimension(64, 24));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termo de Responsabilidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Semibold", 0, 20), new java.awt.Color(48, 63, 56))); // NOI18N
        jPanel3.setOpaque(false);

        medLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel.setForeground(new java.awt.Color(48, 63, 56));
        medLabel.setText("Tem mais animais em casa?");

        maisAnimaisEmCasaButtongroup.add(simOutrosAnimaisButton);
        simOutrosAnimaisButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simOutrosAnimaisButton.setForeground(new java.awt.Color(48, 63, 56));
        simOutrosAnimaisButton.setText("Sim");
        simOutrosAnimaisButton.setEnabled(false);
        simOutrosAnimaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simOutrosAnimaisButtonActionPerformed(evt);
            }
        });

        maisAnimaisEmCasaButtongroup.add(naoOutrosAnimaisButton);
        naoOutrosAnimaisButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoOutrosAnimaisButton.setForeground(new java.awt.Color(48, 63, 56));
        naoOutrosAnimaisButton.setText("Não");
        naoOutrosAnimaisButton.setEnabled(false);
        naoOutrosAnimaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoOutrosAnimaisButtonActionPerformed(evt);
            }
        });

        outrosAnimaisTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        outrosAnimaisTextField.setForeground(new java.awt.Color(48, 63, 56));
        outrosAnimaisTextField.setEnabled(false);

        simCondicoesFinancButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCondicoesFinancButton.setForeground(new java.awt.Color(48, 63, 56));
        simCondicoesFinancButton.setText("Quais ?");

        condicoesButtonGroup.add(naoCondicoes);
        naoCondicoes.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoCondicoes.setForeground(new java.awt.Color(48, 63, 56));
        naoCondicoes.setText("Não");
        naoCondicoes.setEnabled(false);

        condicoesButtonGroup.add(simCondicoes);
        simCondicoes.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCondicoes.setForeground(new java.awt.Color(48, 63, 56));
        simCondicoes.setText("Sim");
        simCondicoes.setEnabled(false);
        simCondicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simCondicoesActionPerformed(evt);
            }
        });

        medLabel2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel2.setForeground(new java.awt.Color(48, 63, 56));
        medLabel2.setText("Tem condições financeiras para levar o animal que está adotando ao veterinário ?");

        medLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel3.setForeground(new java.awt.Color(48, 63, 56));
        medLabel3.setText("Em que tipo de ambiente o animal ficará?");

        ambienteButtonGrouṕ.add(apartamentoButton);
        apartamentoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        apartamentoButton.setForeground(new java.awt.Color(48, 63, 56));
        apartamentoButton.setText("Apartamento");
        apartamentoButton.setEnabled(false);
        apartamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartamentoButtonActionPerformed(evt);
            }
        });

        ambienteButtonGrouṕ.add(casaButton);
        casaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        casaButton.setForeground(new java.awt.Color(48, 63, 56));
        casaButton.setText("Casa");
        casaButton.setEnabled(false);

        ambienteButtonGrouṕ.add(quintalButton);
        quintalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        quintalButton.setForeground(new java.awt.Color(48, 63, 56));
        quintalButton.setText("Quintal");
        quintalButton.setEnabled(false);
        quintalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quintalButtonActionPerformed(evt);
            }
        });

        simCondicoesFinancButton1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simCondicoesFinancButton1.setForeground(new java.awt.Color(48, 63, 56));
        simCondicoesFinancButton1.setText("Quando viajar aonde pensa em deixar o animal?");

        localDuranteViagemTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        localDuranteViagemTextField.setForeground(new java.awt.Color(48, 63, 56));
        localDuranteViagemTextField.setEnabled(false);

        medLabel4.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel4.setForeground(new java.awt.Color(48, 63, 56));
        medLabel4.setText("Se mudar de residência o que fará com o animal?");

        seMudarButtonGroup.add(levoComigoButton);
        levoComigoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        levoComigoButton.setForeground(new java.awt.Color(48, 63, 56));
        levoComigoButton.setText("Levo comigo");
        levoComigoButton.setEnabled(false);
        levoComigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levoComigoButtonActionPerformed(evt);
            }
        });

        seMudarButtonGroup.add(devolvoAdocaoButton);
        devolvoAdocaoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        devolvoAdocaoButton.setForeground(new java.awt.Color(48, 63, 56));
        devolvoAdocaoButton.setText("Devolvo para adoção");
        devolvoAdocaoButton.setEnabled(false);

        seMudarButtonGroup.add(entregoPessoButton);
        entregoPessoButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        entregoPessoButton.setForeground(new java.awt.Color(48, 63, 56));
        entregoPessoButton.setText("Entrego a outra pessoa");
        entregoPessoButton.setEnabled(false);
        entregoPessoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregoPessoButtonActionPerformed(evt);
            }
        });

        medLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel5.setForeground(new java.awt.Color(48, 63, 56));
        medLabel5.setText("Tem consciência de que um animal pode viver até 10, 15, 18 anos? E que se torna responsável por ele durante toda a sua vida?");

        conscienciaButtonGroup.add(simConscienciaButton);
        simConscienciaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        simConscienciaButton.setForeground(new java.awt.Color(48, 63, 56));
        simConscienciaButton.setText("Sim");
        simConscienciaButton.setEnabled(false);
        simConscienciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simConscienciaButtonActionPerformed(evt);
            }
        });

        conscienciaButtonGroup.add(naoConscienciaButton);
        naoConscienciaButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoConscienciaButton.setForeground(new java.awt.Color(48, 63, 56));
        naoConscienciaButton.setText("Não");
        naoConscienciaButton.setEnabled(false);

        medLabel6.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        medLabel6.setForeground(new java.awt.Color(48, 63, 56));
        medLabel6.setText("Já entregou algum animal para adoção/abrigo");

        entregouPraAdocaoButtonGroup.add(entregouAnimalButton);
        entregouAnimalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        entregouAnimalButton.setForeground(new java.awt.Color(48, 63, 56));
        entregouAnimalButton.setText("Sim");
        entregouAnimalButton.setEnabled(false);
        entregouAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregouAnimalButtonActionPerformed(evt);
            }
        });

        entregouPraAdocaoButtonGroup.add(naoEntregouAnimalButton);
        naoEntregouAnimalButton.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        naoEntregouAnimalButton.setForeground(new java.awt.Color(48, 63, 56));
        naoEntregouAnimalButton.setText("Não");
        naoEntregouAnimalButton.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel)
                        .addGap(51, 51, 51)
                        .addComponent(simOutrosAnimaisButton)
                        .addGap(27, 27, 27)
                        .addComponent(naoOutrosAnimaisButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simCondicoesFinancButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outrosAnimaisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(medLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(apartamentoButton)
                                .addGap(27, 27, 27)
                                .addComponent(casaButton)
                                .addGap(31, 31, 31)
                                .addComponent(quintalButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(medLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(simCondicoes)))
                        .addGap(27, 27, 27)
                        .addComponent(naoCondicoes))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simCondicoesFinancButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(localDuranteViagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel4)
                        .addGap(51, 51, 51)
                        .addComponent(levoComigoButton)
                        .addGap(27, 27, 27)
                        .addComponent(devolvoAdocaoButton)
                        .addGap(31, 31, 31)
                        .addComponent(entregoPessoButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel5)
                        .addGap(51, 51, 51)
                        .addComponent(simConscienciaButton)
                        .addGap(27, 27, 27)
                        .addComponent(naoConscienciaButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(medLabel6)
                        .addGap(51, 51, 51)
                        .addComponent(entregouAnimalButton)
                        .addGap(27, 27, 27)
                        .addComponent(naoEntregouAnimalButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel)
                    .addComponent(simOutrosAnimaisButton)
                    .addComponent(naoOutrosAnimaisButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outrosAnimaisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simCondicoesFinancButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel2)
                    .addComponent(simCondicoes)
                    .addComponent(naoCondicoes))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel3)
                    .addComponent(apartamentoButton)
                    .addComponent(casaButton)
                    .addComponent(quintalButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localDuranteViagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simCondicoesFinancButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel4)
                    .addComponent(levoComigoButton)
                    .addComponent(devolvoAdocaoButton)
                    .addComponent(entregoPessoButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel5)
                    .addComponent(simConscienciaButton)
                    .addComponent(naoConscienciaButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medLabel6)
                    .addComponent(entregouAnimalButton)
                    .addComponent(naoEntregouAnimalButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editarCheckBox.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        editarCheckBox.setForeground(new java.awt.Color(48, 63, 56));
        editarCheckBox.setText("Editar adoção");
        editarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCheckBoxActionPerformed(evt);
            }
        });

        excluirAdocaoButton.setBackground(new java.awt.Color(102, 0, 0));
        excluirAdocaoButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        excluirAdocaoButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirAdocaoButton.setText("Excluir");
        excluirAdocaoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        excluirAdocaoButton.setEnabled(false);
        excluirAdocaoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirAdocaoButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        excluirAdocaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAdocaoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dataAdocaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(animaisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(adotanteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editarCheckBox)
                        .addGap(60, 60, 60)
                        .addComponent(salvarAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(excluirAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(465, 465, 465))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(dataAdocaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(adotanteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(animaisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCheckBox)
                    .addComponent(excluirAdocaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void salvarAdocaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAdocaoButtonActionPerformed
        // TODO add your handling code here:
        boolean temOutrosAnimais = false;
        String outrosAnimais = "";
        boolean temOutrosAnimaisSelecionado = false;
        for(AbstractButton button : Collections.list(maisAnimaisEmCasaButtongroup.getElements())){
            if (button.isSelected()) {
                temOutrosAnimaisSelecionado = true;
                if (button.getText().equals("Sim")){
                    temOutrosAnimais = true;
                    outrosAnimais = outrosAnimaisTextField.getText();
                    if (outrosAnimais.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Insira os outros animais.");
                        return;
                    }
                }
                else {
                    temOutrosAnimais = false;
                }
                break;
            }
        }
        
        boolean podeLevarAoVet = false;
        boolean podeLevarAoVetSelecionado = false;
        for( AbstractButton button : Collections.list(condicoesButtonGroup.getElements())){
            if(button.isSelected()){
                podeLevarAoVetSelecionado = true;
                podeLevarAoVet = button.getText().equals("Sim") ? true : false;
                break;
            }
        }
        
        String ambiente = null;
        boolean ambienteSelecionado = false;
        for( AbstractButton button : Collections.list(ambienteButtonGrouṕ.getElements())){
            if(button.isSelected()){
                ambienteSelecionado = true;
                ambiente = button.getText();
                break;
            }
        }
        
        String localDuranteViagem = localDuranteViagemTextField.getText();
        if (localDuranteViagem.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todo o formulário!");
            return;
        }
        
        String oqueFaraSeMudar = null;
        boolean oqueFaraPreenchido = false;
        for( AbstractButton button : Collections.list(seMudarButtonGroup.getElements())){
            if(button.isSelected()){
                oqueFaraPreenchido = true;
                oqueFaraSeMudar = button.getText();
                break;
            }
        }
        
        boolean consciencia = false;
        boolean conscienciaPreenchida = false;
        for( AbstractButton button : Collections.list(conscienciaButtonGroup.getElements())){
            if(button.isSelected()){
                conscienciaPreenchida = true;
                consciencia = button.getText().equals("Sim");
                break;
            }
        }
        
        
        boolean jaEntregouParaAdocao = false;
        boolean jaEntregouPreenchida = false;
        for( AbstractButton button : Collections.list(entregouPraAdocaoButtonGroup.getElements())){
            if(button.isSelected()){
                jaEntregouPreenchida = true;
                jaEntregouParaAdocao = button.getText().equals("Sim");
                break;
            }
            
            
        Termo termoResponsabilidade = new Termo(temOutrosAnimais,outrosAnimais,
        podeLevarAoVet, ambiente, localDuranteViagem, oqueFaraSeMudar, consciencia,
        jaEntregouParaAdocao);
        
        Adotante adotante = animal.getAnimalAdocao().getAdotante();
        
        Adocao adocao = new Adocao(termoResponsabilidade, adotante, animal);
        
        String dataAdocao = dataAdocaoField.getText();
        
        if (!adocao.validarData(dataAdocao).equals("true")){
            JOptionPane.showMessageDialog(null, adocao.validarData(dataAdocao));
            return;
        }
        
        adocao.setDataAdocao(LocalDate.parse(dataAdocao, DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        
        System.out.println("Adoção sendo alterada no sistema...");
        animal.setAnimalAdocao(adocao);
        ArrayList <Adocao> animaisAdotados = adotante.getAnimaisAdotados();
        animaisAdotados.remove(adocaoOriginal);
        animaisAdotados.add(adocao);
        adotante.setAnimaisAdotados(animaisAdotados);
        
        handleJson.atualizarAnimal(animal.getAnimalID(), animal);
        adotanteDAO.atualizarAdotante(adotante.getCpf(), adotante);
        System.out.println("Adoção alterada com sucesso");
        Historico historico = new Historico(animal, adocao, true, false);
        try {
            handleJson.AddHistoricoNoArquivo(historico);
        } catch (IOException ex) {
            System.out.println("Erro ao tentar adicionar a modificação da adoção ao histórico.");
        }
        
        System.out.println("Adoção alterada com sucesso!");
        JOptionPane.showMessageDialog(null, "Adoção alterada com sucesso!");
        this.dispose();
    }
    }//GEN-LAST:event_salvarAdocaoButtonActionPerformed

    private void adotanteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adotanteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adotanteBoxActionPerformed

    private void dataAdocaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAdocaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAdocaoFieldActionPerformed

    private void simOutrosAnimaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simOutrosAnimaisButtonActionPerformed
        // TODO add your handling code here:
        outrosAnimaisTextField.setEnabled(true);
    }//GEN-LAST:event_simOutrosAnimaisButtonActionPerformed

    private void naoOutrosAnimaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoOutrosAnimaisButtonActionPerformed
        // TODO add your handling code here:
        outrosAnimaisTextField.setEnabled(false);
        outrosAnimaisTextField.setText("");
    }//GEN-LAST:event_naoOutrosAnimaisButtonActionPerformed

    private void simCondicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simCondicoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simCondicoesActionPerformed

    private void apartamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartamentoButtonActionPerformed

    private void quintalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quintalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quintalButtonActionPerformed

    private void levoComigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levoComigoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levoComigoButtonActionPerformed

    private void entregoPessoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregoPessoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entregoPessoButtonActionPerformed

    private void simConscienciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simConscienciaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simConscienciaButtonActionPerformed

    private void entregouAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregouAnimalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entregouAnimalButtonActionPerformed

    private void editarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCheckBoxActionPerformed
        // TODO add your handling code here:
        if (editarCheckBox.isSelected()){
         
            for (AbstractButton button : Collections.list(maisAnimaisEmCasaButtongroup.getElements())){
                button.setEnabled(true);
            }
            for (AbstractButton button : Collections.list(condicoesButtonGroup.getElements())){
                button.setEnabled(true);
            }
            for (AbstractButton button : Collections.list(ambienteButtonGrouṕ.getElements())){
                button.setEnabled(true);
            }
            for (AbstractButton button : Collections.list(seMudarButtonGroup.getElements())){
                button.setEnabled(true);
            }
            for (AbstractButton button : Collections.list(conscienciaButtonGroup.getElements())){
                button.setEnabled(true);
            }
            for (AbstractButton button : Collections.list(entregouPraAdocaoButtonGroup.getElements())){
                button.setEnabled(true);
            }
            
            salvarAdocaoButton.setVisible(true);
            excluirAdocaoButton.setVisible(true);
            salvarAdocaoButton.setEnabled(true);
            excluirAdocaoButton.setEnabled(true);
            excluirAdocaoButton.setVisible(true);
            dataAdocaoField.setEnabled(true);
            localDuranteViagemTextField.setEnabled(true);
            outrosAnimaisTextField.setEnabled(true);
        }
        else {
            for (AbstractButton button : Collections.list(maisAnimaisEmCasaButtongroup.getElements())){
                button.setEnabled(false);
            }
            for (AbstractButton button : Collections.list(condicoesButtonGroup.getElements())){
                button.setEnabled(false);
            }
            for (AbstractButton button : Collections.list(ambienteButtonGrouṕ.getElements())){
                button.setEnabled(false);
            }
            for (AbstractButton button : Collections.list(seMudarButtonGroup.getElements())){
                button.setEnabled(false);
            }
            for (AbstractButton button : Collections.list(conscienciaButtonGroup.getElements())){
                button.setEnabled(false);
            }
            for (AbstractButton button : Collections.list(entregouPraAdocaoButtonGroup.getElements())){
                button.setEnabled(false);
            }
            
            salvarAdocaoButton.setVisible(false);
            excluirAdocaoButton.setVisible(false);
            salvarAdocaoButton.setEnabled(false);
            excluirAdocaoButton.setEnabled(false);
            dataAdocaoField.setEnabled(false);
            localDuranteViagemTextField.setEnabled(false);
            outrosAnimaisTextField.setEnabled(false);
        }
    }//GEN-LAST:event_editarCheckBoxActionPerformed

    private void excluirAdocaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAdocaoButtonActionPerformed
        // TODO add your handling code here:
        animal.setAnimalAdocao(null);
        Adotante adotante = adocaoOriginal.getAdotante();
        
        ArrayList<Adocao> animaisAdotados = adotante.getAnimaisAdotados();
        animaisAdotados.remove(adocaoOriginal);
        adotante.setAnimaisAdotados(animaisAdotados);
        
        Historico historico = new Historico(animal, adocaoOriginal, false, true);
        try {
            handleJson.AddHistoricoNoArquivo(historico);
        } catch (IOException ex) {
            System.out.println("Erro ao tentar adicionar a adoção ao histórico.");
        }
        this.dispose();
    }//GEN-LAST:event_excluirAdocaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adotanteBox;
    private javax.swing.ButtonGroup ambienteButtonGrouṕ;
    private javax.swing.JComboBox<String> animaisBox;
    private javax.swing.JRadioButton apartamentoButton;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JRadioButton casaButton;
    private javax.swing.ButtonGroup condicoesButtonGroup;
    private javax.swing.ButtonGroup conscienciaButtonGroup;
    private javax.swing.JFormattedTextField dataAdocaoField;
    private javax.swing.JRadioButton devolvoAdocaoButton;
    private javax.swing.JCheckBox editarCheckBox;
    private javax.swing.JRadioButton entregoPessoButton;
    private javax.swing.JRadioButton entregouAnimalButton;
    private javax.swing.ButtonGroup entregouPraAdocaoButtonGroup;
    private javax.swing.JButton excluirAdocaoButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton levoComigoButton;
    private javax.swing.JTextField localDuranteViagemTextField;
    private javax.swing.ButtonGroup maisAnimaisEmCasaButtongroup;
    private javax.swing.JLabel medLabel;
    private javax.swing.JLabel medLabel2;
    private javax.swing.JLabel medLabel3;
    private javax.swing.JLabel medLabel4;
    private javax.swing.JLabel medLabel5;
    private javax.swing.JLabel medLabel6;
    private javax.swing.JRadioButton naoCondicoes;
    private javax.swing.JRadioButton naoConscienciaButton;
    private javax.swing.JRadioButton naoEntregouAnimalButton;
    private javax.swing.JRadioButton naoOutrosAnimaisButton;
    private javax.swing.JTextField outrosAnimaisTextField;
    private javax.swing.JRadioButton quintalButton;
    private javax.swing.JButton salvarAdocaoButton;
    private javax.swing.ButtonGroup seMudarButtonGroup;
    private javax.swing.JRadioButton simCondicoes;
    private javax.swing.JLabel simCondicoesFinancButton;
    private javax.swing.JLabel simCondicoesFinancButton1;
    private javax.swing.JRadioButton simConscienciaButton;
    private javax.swing.JRadioButton simOutrosAnimaisButton;
    // End of variables declaration//GEN-END:variables
}
